package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/sasakitimaru/git_gql/graph/model"
)

type queryResolver struct{ *Resolver }

func (r *queryResolver) User(ctx context.Context, name string) (*model.User, error) {
	return r.srv.UserService().GetUserByName(ctx, name)
}
